#!/bin/bash

source ".pathDirFile";
for sample in `(cat $samples)`; do
  mkdir -p $kallistoOutputDir/$sample
  forward_read=$(ls $dataDir/$sample | grep R1)
  reverse_read=$(ls $dataDir/$sample | grep R2)
  kallisto quant -i $kallistoIndexFile -o $kallistoOutputDir/$sample -b 100 $dataDir/$sample/$forward_read $dataDir/$sample/$reverse_read  
done
